# 02 Preprocesamiento de datos

En esta etapa se transforma el dataset crudo en un conjunto estructurado y apto para entrenamiento supervisado.

El objetivo principal es garantizar consistencia estadística, compatibilidad matemática con algoritmos de machine learning y minimizar ruido analítico que pueda deteriorar la capacidad predictiva.

El preprocesamiento constituye una fase crítica porque la calidad del modelo depende directamente de la calidad del dato de entrada.

## 1. Importar Librerias

In [19]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

## 2. Carga del Dataset

In [20]:
df = pd.read_csv('../Data/Raw/Telco-Customer-Churn.csv')
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

## 3. Inspección inicial

In [21]:
df.shape

(7043, 21)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [23]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [24]:
#Se realiza el cambio de la variable TotalCharges de object a valor numerico

df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
df.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

* Al realizar el cambio de la variable TotalCharges a numerica, se identifica que cuenta con registros nulos que deben de ser tratados.

## 4. Tratamiento de dataset

### Eliminar registros nulos

In [25]:
df.dropna(inplace=True)
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [26]:
df.shape

(7032, 21)

* Posterior al tratamiento de la informacion derivado de la eliminacion de los datos nulos, se pudo identificar una modificacion en el numero total de registros contenidos en el dataset, sin embargo al ser menor no se considera que comprometa los resultados del analisis. Estos se pueden considerar que corresponder a clientes recién incorporados sin historial acumulado.

### Eliminar variable costumerID

Derivado del analisis de la informacion, se considera que para los analisis posteriores asi como las predicciones y creacion de modelos de predictivos

In [27]:
df.drop('customerID', axis=1, inplace=True)
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

## 5. Codificación de variable objetivo

La variable objetivo en este caso Churn, se cambiara de tipo de dato a binario para poder tratar mas facil la informacion haciendola interpretable por algoritmos de clasificación.

In [28]:
df['Churn'] = df['Churn'].map({
    'No': 0,
    'Yes': 1
})

df['Churn'].value_counts()

Churn
0    5163
1    1869
Name: count, dtype: int64

## 6. Identificar variables categóricas

In [30]:
#Identificar aquellas variables que requieren que se realice codificación para poder realizar un tratamiento matemático.

df.select_dtypes(include='object').columns

Index(['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod'],
      dtype='object')

In [34]:
# Convertir variables categóricas en representación numérica evitando relaciones ordinales artificiales.

df_encoded = pd.get_dummies(df, drop_first=True)
df_encoded.shape

(7032, 31)

In [35]:
df_encoded.head()

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,Churn,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,29.85,29.85,0,False,True,False,False,True,...,False,False,False,False,False,False,True,False,True,False
1,0,34,56.95,1889.50,0,True,False,False,True,False,...,False,False,False,False,True,False,False,False,False,True
2,0,2,53.85,108.15,1,True,False,False,True,False,...,False,False,False,False,False,False,True,False,False,True
3,0,45,42.30,1840.75,0,True,False,False,False,True,...,False,False,False,False,True,False,False,False,False,False
4,0,2,70.70,151.65,1,False,False,False,True,False,...,False,False,False,False,False,False,True,False,True,False

## 7. Separación de variables

In [36]:
# Definir matriz de entrada (X) y variable objetivo (y) para entrenamiento supervisado.

X = df_encoded.drop('Churn', axis=1)
y = df_encoded['Churn']

X.shape, y.shape

((7032, 30), (7032,))

## 8. Train-Test

In [37]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

print(y_train.value_counts(normalize=True))
print(y_test.value_counts(normalize=True))

(5625, 30)
(1407, 30)
Churn
0    0.734222
1    0.265778
Name: proportion, dtype: float64
Churn
0    0.734186
1    0.265814
Name: proportion, dtype: float64

## 9. Escalado de variables

In [38]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

X_train_scaled[:5]

array([[-0.43931886,  1.3218163 ,  0.98155578,  1.6599004 ,  0.99627361,
         1.02831173,  1.5291432 ,  0.32754155, -0.32754155,  1.16554303,
         1.12490211, -0.52296156, -0.52296156,  1.57642955, -0.52296156,
         1.36157309, -0.52296156,  1.37605179, -0.52296156,  1.54681665,
        -0.52296156, -0.79787323, -0.52296156, -0.79996356, -0.51578723,
         1.77260282, -1.21302973,  1.90515869, -0.71617747, -0.5394682 ],
       [-0.43931886, -0.26741023, -0.97154551, -0.56225219,  0.99627361,
        -0.97246775, -0.65396099, -3.05304781,  3.05304781, -0.85796918,
        -0.88896624, -0.52296156, -0.52296156, -0.63434487, -0.52296156,
        -0.7344446 , -0.52296156,  1.37605179, -0.52296156,  1.54681665,
        -0.52296156, -0.79787323, -0.52296156, -0.79996356, -0.51578723,
        -0.56414217, -1.21302973, -0.52489066,  1.39630196, -0.5394682 ],
       [-0.43931886,  1.4440645 ,  0.83706615,  1.75610395, -1.00374033,
         1.02831173, -0.65396099,  0.32754155, -0.32754155,  1.16554303,
         1.12490211, -0.52296156, -0.52296156, -0.63434487, -0.52296156,
         1.36157309, -0.52296156,  1.37605179, -0.52296156,  1.54681665,
        -0.52296156, -0.79787323, -0.52296156, -0.79996356, -0.51578723,
         1.77260282, -1.21302973,  1.90515869, -0.71617747, -0.5394682 ],
       [-0.43931886, -1.20464639,  0.6410917 , -0.90832567,  0.99627361,
        -0.97246775, -0.65396099,  0.32754155, -0.32754155, -0.85796918,
         1.12490211, -0.52296156, -0.52296156, -0.63434487, -0.52296156,
         1.36157309, -0.52296156, -0.72671684, -0.52296156, -0.64648903,
        -0.52296156, -0.79787323, -0.52296156,  1.25005695, -0.51578723,
        -0.56414217, -1.21302973, -0.52489066,  1.39630196, -0.5394682 ],
       [-0.43931886,  0.66982593, -0.80878707, -0.10156068, -1.00374033,
         1.02831173, -0.65396099, -3.05304781,  3.05304781, -0.85796918,
        -0.88896624, -0.52296156, -0.52296156,  1.57642955, -0.52296156,
        -0.7344446 , -0.52296156, -0.72671684, -0.52296156, -0.64648903,
        -0.52296156,  1.25333194, -0.52296156, -0.79996356, -0.51578723,
        -0.56414217, -1.21302973, -0.52489066, -0.71617747, -0.5394682 ]])

In [39]:
print('Train:', X_train_scaled.shape)
print('Test:', X_test_scaled.shape)

Train: (5625, 30)
Test: (1407, 30)

## 10. Exportar datasets procesados

In [41]:
pd.DataFrame(X_train_scaled).to_csv('../data/processed/X_train.csv', index=False)
pd.DataFrame(X_test_scaled).to_csv('../data/processed/X_test.csv', index=False)
y_train.to_csv('../data/processed/y_train.csv', index=False)
y_test.to_csv('../data/processed/y_test.csv', index=False)

## 11. Conclusiones

**Hallazgos técnicos*

El dataset mostró alta calidad estructural con anomalías mínimas.

Transformaciones críticas aplicadas
conversión numérica
depuración
binarización categórica
división estratificada
normalización estadística
Impacto para modelado

El conjunto final está listo para entrenamiento comparativo de modelos supervisados.